name: bnhcoin
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - jsonpickle # conda-forge
  - flask
  - pycrypto
  - requests
  - flask-sqlalchemy
  - flask-bcrypt
  - flask-login
  - flask-wtf
  - email_validator
